# Generated by Django 3.2.4 on 2021-06-13 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoit',
            name='section',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='todoit.section'),
        ),
    ]
