# Generated by Django 3.2.4 on 2021-06-13 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoit', '0002_alter_todoit_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoit',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todoit.section'),
        ),
    ]
